apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: oasa-telemat
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: oasa-telemat.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oasa-server-svc
            port:
              number: 80