apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mysql-alter
  namespace: oasa-telemat
configMapGenerator:
  - name: mysql-schema-alter
    namespace: oasa-telemat
    files:
      - resources/alter.sql
resources:
  - deployment.yaml
generatorOptions:
  disableNameSuffixHash: true # use a static name