# ---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mysql-entry
  name: configmap-entry
  namespace: oasa-telemat
data:
  entrypoint.sh: |-
    #!/bin/bash
    
    while ! mysqladmin ping -u root --silent; do
        echo "🟠 Wait for MySQL to be ready..."
        sleep 1
    done
    
    echo "🟢 MySQL is ready."
    echo "🟦 Current user: $(whoami)"

    mysql -u root -e "source /var/db/config/oasa-telemat/mysql-schema-config.sql"
    
    export MYSQL_PWD=$(echo $MYSQL_ROOT_PASSWORD)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-depl
  name: mysql-depl
  namespace: oasa-telemat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-depl
  template:
    metadata:
      labels:
        app: mysql-depl
    spec:
      containers:
      - name: mysql
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "500Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
            ephemeral-storage: "1Gi"
        image: mysql:8.4
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-password
          # - name: MYSQL_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: mysql-secret
          #       key: username
          # - name: MYSQL_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: mysql-secret
          #       key: password 
        ports:
          - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pvc-vol
        - mountPath: /var/db/config/oasa-telemat
          name: mysql-schema-config-vol
        - name: configmap-entry-vol
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
          failureThreshold: 2
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/entrypoint.sh"
      volumes:
      - name: mysql-pvc-vol
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-schema-config-vol
        configMap:
          name: mysql-schema-config
          defaultMode: 420
          items:
          - key: schema_v2.sql
            path: mysql-schema-config.sql
      - name: configmap-entry-vol
        configMap:
          defaultMode: 0700
          name: configmap-entry
