apiVersion: batch/v1
kind: CronJob
metadata:
  name: oasa-cronjob
  namespace: oasa-telemat
spec:
  schedule: "*/30 * * * *"  # Runs every day at 21pm
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: oasa-job-container
            image: oulisnikos/oasa-cron:0.0.2-prod
            envFrom:
            - configMapRef:
                name: enviroment-config-job
            volumeMounts:
            - name: job-logs
              mountPath: /var/log/oasa
          volumes:
          - name: job-logs
            persistentVolumeClaim:
                claimName: job-logs-pvc
          restartPolicy: Never
          initContainers:
          - name: wait-for-mysql-pod
            image: busybox:1.28
            args:
            - /bin/sh
            - -c
            - until telnet mysql-svc 3306; do echo waiting for mysql-service; sleep 2; done;