apiVersion: batch/v1
kind: CronJob
metadata:
  name: oasa-cronjob
  namespace: oasa-telemat
spec:
  schedule: "*/30 * * * *"  # Runs every day at 21pm
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: oasa-job-container
            image: localhost:5000/oasa-job:0.0.1
            envFrom:
            - configMapRef:
                name: enviroment-config-job
          restartPolicy: Never
          initContainers:
          - name: wait-for-mysql-pod
            image: busybox:1.28
            args:
            - /bin/sh
            - -c
            - until telnet mysql-svc 3306; do echo waiting for mysql-service; sleep 2; done;