apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-logs-pvc
  namespace: oasa-telemat
  labels:
    pvc: job-logs-pvc
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi