apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: oasa-telemat 
  labels:
    pvc: keycloak-pvc
spec:
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce